name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: STM32CubeIDE-portable-${{ github.ref_name }}.zip
      version: v1.6.1
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          cd ${{ env.targetZip }} &&^
          7z x st-stm32cubeide_1.16.1_22882_20240916_0822_x86_64.zip.001 -y &&^
          7z x st-stm32cubeide_1.16.1_22882_20240916_0822_x86_64.exe -y &&^
          dir
          
      - shell: cmd
        run: xcopy /H /Y /C "stm32cubeide.exe.Portable.cmd" "${{ env.targetZip }}\STM32CubeIDE"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "${{ env.targetZip }}/STM32CubeIDE"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}/STM32CubeIDE/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
