name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: STM32CubeIDE-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: bash
        run: |
          curl 'https://www.st.com/content/ccc/resource/technical/software/sw_development_suite/group1/d4/73/26/34/82/38/49/e9/stm32cubeide-win/files/st-stm32cubeide_1.16.1_22882_20240916_0822_x86_64.exe.zip/jcr:content/translations/en.st-stm32cubeide_1.16.1_22882_20240916_0822_x86_64.exe.zip' \
            -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
            -H 'accept-language: en-US,en;q=0.9' \
            -H 'priority: u=0, i' \
            -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "Windows"' \
            -H 'sec-fetch-dest: document' \
            -H 'sec-fetch-mode: navigate' \
            -H 'sec-fetch-site: none' \
            -H 'sec-fetch-user: ?1' \
            -H 'upgrade-insecure-requests: 1' \
            -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
            -L --output installer.zip

      - name: installer
        shell: cmd
        run: |
          7z x installer.zip -o"installation" -y &&^
          cd installation &&^
          7z x st-stm32cubeide_1.16.1_22882_20240916_0822_x86_64.exe -y &&^
          dir
          
      - shell: cmd
        run: xcopy /H /Y /C "stm32cubeide.exe.Portable.cmd" "installation\STM32CubeIDE"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation/STM32CubeIDE"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/STM32CubeIDE/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
